# Use the official Python image as the base image
FROM python:latest

# Install the required packages
RUN pip install numpy pandas matplotlib pillow pyinotify requests

# Set the working directory
WORKDIR /

# Run your Python script or start a shell
CMD ["python"]
